version: 2.1
orbs:
  docker: circleci/docker@2.2.0

jobs:
  myjob:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - run:
          name: Build and Push Docker Image
          command: |
            # Build the Docker image
            docker build -t demo-app .

            # TAG docker image
            docker tag demo-app $DOCKERHUB_USERNAME/demo-app:v1

            # Log in to Docker Hub
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

            # Push the Docker image to Docker Hub
            docker push $DOCKERHUB_USERNAME/demo-app:v1

workflows:
  myjob-workflow:
    jobs:
      - myjob
