version: 2.1

jobs:
  myjob:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: hello-world
          command: echo "my first circle-ci job"

  secondjob:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.8
      - run:
          name: second-world
          command: |
            echo "my second circle-ci job"
            docker build -t myimg:latest .

workflows:
  myjob-workflow:
    jobs:
      - myjob
      - secondjob
