version: 2.1
orbs:
  docker: circleci/docker@2.2.0

jobs:
  myjob:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: hello-world
          command: echo "my first circle-ci job"

  dockerbuild:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - checkout
      - docker/build:
          image: demo-app
          tag: v1
          registry: $DOCKERHUB_USERNAME

      - run:
          name: List Docker Images
          command: docker images

  docker-push:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker
      - checkout
      - docker/push:
          image: demo-app
          registry: $DOCKERHUB_USERNAME
          tag: v1

workflows:
  myjob-workflow:
    jobs:
      - myjob
      - dockerbuild
      - docker-push

