version: 2.1
orbs:
  docker: circleci/docker@2.2.0

jobs:
  myjob:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: hello-world
          command: echo "my first circle-ci job"

  dockerbuild:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - checkout
      - docker/build:
          image: demo-app
          tag: v1
          registry: $DOCKERHUB_USERNAME
          propagate-environment: true
          propagate-registry-permissions: true
          propagate-tags-permissions: true
    environment:
      DEMO_IMAGE: demo-app:v1

  docker-push:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker
      - checkout
      - run: 
          name: List Docker Images
          command: docker images

      - run:
          name: Docker Push
          command: docker push $DOCKERHUB_USERNAME/$DEMO_IMAGE

workflows:
  myjob-workflow:
    jobs:
      - myjob
      - dockerbuild:
          requires:
            - myjob
      - docker-push:
          requires:
            - dockerbuild
