version: 2.1

jobs:
  hello-world:
    docker:
      - image:  cimg/base:stable
    steps:
      - checkout
      - run:
        name: "say hello world"
        command: "echo hello,world"

workflows:
  say-hello-workflow:
    jobs:
      hello-world        

