version: 2.1
orbs:
  docker: circleci/docker@1.7.0

jobs:
  myjob:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: hello-world
          command: echo "my first circle-ci job"

  secondjob:
    docker:
      - image: cimg/base:stable
    steps:
      - docker/build:
          image: demo-app
          tag: v1

  pushjob:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Configure Docker credentials
          command: |
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - docker/push:
          image: demo-app
          registry: simrankhot
          tag: v1

workflows:
  myjob-workflow:
    jobs:
      - myjob
      - secondjob
      - pushjob
