version: 2.1
orbs:
  docker: circleci/docker@1.7.0

jobs:
  myjob:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: hello-world
          command: echo "my first circle-ci job"
  secondjob:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - checkout
      - docker/build:
          dockerfile: Dockerfile
          image: myimage
          tag: latest

workflows:
  myjob-workflow:
    jobs:
      - myjob
      - secondjob
